<template>
    <main>       
        <section class="sec-padding">
            <div class="container"> 
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12 col-lg-12">
                        <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
                            <h3>Terms and Conditions</h3>
                            <p><b>Last Updated: September 3, 2021</b></p>
                            <p>
                                Nanny Parent Connection provides various platform tools for parents seeking child care to connect with 
                                and hire experienced nannies, sitters, mother’s helpers and au pairs in the Puget Sound region. Nanny 
                                Parent Connection does not hire or employ care providers nor are we responsible for the actions of 
                                any of our members. If you are seeking child care through our site or associated sites, you are solely 
                                responsible for the care provider that you choose to hire. You are also responsible for following all 
                                applicable laws in relation to the employer-employee relationship that you create.
                            </p>
                            <p>
                                <strong>1. BINDING EFFECT.</strong> This is a binding agreement between you and Nanny Parent Connection  LLC (”us”, ”we”, ”Company”). By using the Internet site located at https://nannyparentconnection.com 
                                (the ”Site”), you agree to abide by these Terms of Use. If at any time you find these Terms of Use unacceptable, you must immediately leave the Site and cease all use of it.
                            </p>
                            <p>
                                <strong>2. PRIVACY POLICY.</strong> We respect your privacy and permit you to control the treatment of your personal information. A complete statement of our current privacy policy can be found by 
                            <router-link to="/privacy-policy" rel="Privacy Policy">clicking here</router-link>. 
                                Our privacy policy is expressly incorporated into this Agreement by this reference.
                            </p>
                            <p>
                                <strong>3. GOVERNING LAW.</strong> These Terms of Use shall be construed in accordance with and governed by the laws of the State of Washington and the United States, without reference to rules regarding conflicts of law. This Site is intended for use by individuals based in the United States of America.
                            </p>
                            <p>
                                <strong>4. MINIMUM AGE.</strong> You must be at least 18 years old to access and participate on this Site. You guarantee and warrant you are at least 18 years old and are able to enter into this Agreement from a legal perspective.
                            </p>
                            <p>
                                <strong>5. EMAIL COMMUNICATIONS.</strong> When you contact us or access our Site, you expressly consent and agree to receive electronic mail from us. These email communications may be commercial or non-commercial in nature. Non-commercial emails may include, but are not limited to, administrative issues and announcements of changes to these Terms, the Privacy Policy or other Site documentation. To stop receiving these emails, please <a title="contact us here" href="mailto:info@nannyparentconnection.com?subject=Email Communications from Nanny Parent Connection">contact us here</a>.
                            </p>
                            <p>
                                <strong>6. USE OF SOFTWARE.</strong> Company may make certain software available to you from the Site. If you download software from the Site, the software, including all files and images contained in or generated by the software, and accompanying data (collectively, ”Software”) are deemed to be licensed to you by Company, for your personal, noncommercial, home use only. Company does not transfer either the title or the intellectual property rights to the Software, and Company retains full and complete title to the Software as well as all intellectual property rights therein. You may not sell, redistribute, or reproduce the Software, nor may you decompile, reverse-engineer, disassemble, or otherwise convert the Software to a human-perceivable form. All trademarks and logos are owned by Company or its licensors and you may not copy or use them in any manner.
                            </p>
                            <p>
                                <strong>7. USER CONTENT.</strong> By posting, downloading, displaying, performing, transmitting, or otherwise distributing information or other content (”User Content”) to the Site, you are granting Company, its affiliates, officers, directors, employees, consultants, agents, and representatives a permanent, non-exclusive license to use User Content in connection with the operation of the Internet businesses of Company, its affiliates, officers, directors, employees, consultants, agents, and representatives, including without limitation, a right to copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate, and reformat User Content. You will not be compensated for any User Content. You agree that Company may publish or otherwise disclose your name in connection with your User Content. By posting User Content on the Site, you warrant and represent that you own the rights to the User Content or are otherwise authorized to post, distribute, display, perform, transmit, or otherwise distribute User Content.
                            </p>
                            <p>
                                <strong>8. COMPLIANCE WITH INTELLECTUAL PROPERTY LAWS.</strong> When accessing the Site, you agree to obey the law and to respect the intellectual property rights of others. Your use of the Site is at all times governed by and subject to laws regarding copyright ownership and use of intellectual property. You agree not to upload, download, display, perform, transmit, or otherwise distribute any information or content (collectively, ”Content”) in violation of any third party’s copyrights, trademarks, or other intellectual property or proprietary rights. You agree to abide by laws regarding copyright ownership and use of intellectual property, and you shall be solely responsible for any violations of any relevant laws and for any infringements of third party rights caused by any Content you provide or transmit, or that is provided or transmitted using your User ID. The burden of proving that any Content does not violate any laws or third party rights rests solely with you. All Digital Millennium Copyright Act matters are processed pursuant to our DMCA Policy, which you may <a title="access here" href="#">access here.</a>
                            </p>
                            <p>
                                <strong>9. INAPPROPRIATE CONTENT.</strong> You agree not to upload, download, display, perform, transmit, or otherwise distribute any Content that (a) is libelous, defamatory, obscene, pornographic, abusive, or threatening; (b) advocates or encourages conduct that could constitute a criminal offense, give rise to civil liability, or otherwise violate any applicable local, state, national, or foreign law or regulation; or (c) provides medical or legal advice to other users. Company reserves the right to terminate your receipt, transmission, or other distribution of any such material using the Site, and, if applicable, to delete any such material from its servers. Company intends to cooperate fully with any law enforcement officials or agencies in the investigation of any violation of these Terms or of any applicable laws.
                            </p>
                            <p>
                                <strong>10. NO WARRANTIES.</strong> WE HEREBY DISCLAIM ALL WARRANTIES. WE ARE MAKING THE SITE AVAILABLE ”AS IS” WITHOUT WARRANTY OF ANY KIND. YOU ASSUME THE RISK OF ANY AND ALL DAMAGE OR LOSS FROM USE OF, OR INABILITY TO USE, THE SITE OR THE SERVICE. TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, REGARDING THE SITE, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SITE OR THE SERVICE WILL MEET YOUR REQUIREMENTS OR THAT THE OPERATION OF THE SITE OR THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE.
                            </p>
                            <p>
                                <strong>11. LIMITED LIABILITY.</strong> OUR LIABILITY TO YOU IS LIMITED. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL WE BE LIABLE FOR DAMAGES OF ANY KIND (INCLUDING, BUT NOT LIMITED TO, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, LOST PROFITS, OR LOST DATA, REGARDLESS OF THE FORESEEABILITY OF THOSE DAMAGES) ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SITE OR ANY OTHER MATERIALS OR SERVICES PROVIDED TO YOU BY US. This limitation shall apply regardless of whether the damages arise out of breach of contract, tort, or any other legal theory or form of action.
                            </p>
                            <p>
                                <strong>12. AFFILIATED SITES.</strong> We have no control over and no liability for any third party websites or materials. We work with a number of partners whose Internet sites may be linked with the Site. Because we have no control over the content and performance of these partner and affiliate sites, we make no guarantees about the accuracy, currency, content, or quality of the information provided by such sites, and we assume no responsibility for unintended, objectionable, inaccurate, misleading, or unlawful content that may reside on those sites. Similarly, from time to time in connection with your use of the Site, you may have access to content items (including, but not limited to, websites) that are owned by third parties. You acknowledge and agree that we make no guarantees about, and assumes no responsibility for, the accuracy, currency, content, or quality of this third party content, and that, unless expressly provided otherwise, these Terms of Use shall govern your use of any and all third party content.
                            </p>
                            <p>
                                <strong>13. PROHIBITED USES.</strong> We impose certain restrictions on your permissible use of the Site. You are prohibited from violating or attempting to violate any security features of the Site, including, without limitation, (a) accessing content or data not intended for you, or logging onto a server or account that you are not authorized to access; (b) attempting to probe, scan, or test the vulnerability of the Site, or any associated system or network, or to breach security or authentication measures without proper authorization; (c) interfering or attempting to interfere with service to any user, host, or network, including, without limitation, by means of submitting a virus to the Site, overloading, ”flooding,” ”spamming,” ”mail bombing,” ”crashing” or instituting a ”DDOS” attack on the Site; (d) using the Site to send unsolicited e-mail, including, without limitation, promotions, or advertisements for products or services; (e) forging any TCP/IP packet header or any part of the header information in any e-mail or in any posting using the Site; or (f) attempting to modify, reverse-engineer, decompile, disassemble, or otherwise reduce or attempt to reduce to a human-perceivable form any of the source code used by us in providing the Site. Any violation of system or network security may subject you to civil and/or criminal liability.
                            </p>
                            <p>
                                <strong>14. INDEMNITY.</strong> You agree to indemnify us for certain of your acts and omissions. You agree to indemnify, defend, and hold harmless Company, its affiliates, officers, directors, employees, consultants, agents, and representatives from any and all third party claims, losses, liability, damages, and/or costs (including reasonable attorney fees and costs) arising from your access to or use of the Site, your violation of these Terms of Use, or your infringement, or infringement by any other user of your account, of any intellectual property or other right of any person or entity. We will notify you promptly of any such claim, loss, liability, or demand, and will provide you with reasonable assistance, at your expense, in defending any such claim, loss, liability, damage, or cost.
                            </p>
                            <p>
                                <strong>15. COPYRIGHT.</strong> All contents of Site or Service are: Copyright © 2020 Nanny Parent Connection LLC.
                            </p>
                                <p>
                                    <strong>16. SEVERABILITY; WAIVER.</strong> If, for whatever reason, a court of competent jurisdiction finds any term or condition in these Terms of Use to be unenforceable, all other terms and conditions will remain unaffected and in full force and effect. No waiver of any breach of any provision of these Terms of Use shall constitute a waiver of any prior, concurrent, or subsequent breach of the same or any other provisions hereof, and no waiver shall be effective unless made in writing and signed by an authorized representative of the waiving party.
                                </p>
                                <p>
                                    <strong>17. NO LICENSE.</strong> Nothing contained on the Site should be understood as granting you a license to use any of the trademarks, service marks, or logos owned by us or by any third party.
                                </p>
                                <p>
                                    <strong>18. UNITED STATES USE ONLY.</strong> The Site is controlled and operated by the Company from its offices in the State of Washington. The domain of the website is registered in the United States and the Site is hosted in the United States. The intended audience for this Site consists of individuals in the United States only. Company makes no representation that any of the materials or the services to which you have been given access are available or appropriate for use in other locations. Your use of or access to the Site should not be construed as Company’s purposefully availing itself of the benefits or privilege of doing business in any state or jurisdiction other than Washington and the United States.
                                </p>
                                <p>
                                    <strong>19. SUBSCRIPTION POLICY.</strong>
                                </p>
                                <p>(a) Monthly: The subscription starts after the initial payment is processed. Subscription will continue without renewal notice until canceled by the user. The monthly subscription rate is subject to change, but you will be notified of any modifications to your monthly rate with the option to cancel in accordance with these terms. Your initial payment and subsequent membership renewal payments are non-refundable. Cancel your subscription at any time after the initial payment is paid by visiting your account page or by contacting <a title="us here" href="mailto:billing@nannyparentconnection.com">us here</a> within three (3) days prior to your monthly billing date; otherwise, the cancellation will be effective from the next monthly billing date.
                            </p>
                            <p>
                                (b) Annual: The subscription starts after the initial payment is processed. Your initial payment and subsequent membership renewal payments are non-refundable. You will be charged the annual rate stated at the time of purchase as one lump sum. Your subscription will renew automatically, on your annual renewal date, until you cancel. An email reminding you that your subscription will renew is sent 30 days before your annual renewal date. If you did not receive the email reminder, please contact us immediately. The annual subscription rate is subject to change, but you will be notified of any modifications to your annual rate with the option to cancel in accordance with these terms. Cancellations can be made by visiting your account page or by contacting <a title="Email us on" href="mailto:billing@nannyparentconnection.com">us here</a> within three (3) days prior to your annual billing renewal date; otherwise, the cancellation will be effective from the next annual billing date.
                            </p>
                            <p>
                                (c) One Month Only: Access starts after the initial payment is processed. The payment is non-refundable.
                            </p>
                            <p>
                                (d) Learning Guide Service: Access starts after the initial payment is processed. Nanny Parent Connection will search, present and complete due diligence for one (1) Learning Guide candidate for your family or microschool. Due to the extensive number of hours and resources that our team commits to your search, refunds are only issued in two cases:
                            </p>
                            <p>
                                – If, within 24 hours of purchasing access to our Learning Guide Service, you decide that this service will not work for you, or;
                            </p>
                            <p>
                                – If our team has not presented any Learning Guide candidates to you within thirty (30) days from the date that you purchased access to the Learning Guide Service.
                            </p>
                            <p>
                                If any of the above events have occurred, immediately contact us via email by <a title="clicking here" href="mailto:billing@nannyparentconnection.com">clicking here</a> with your name, email address, mailing address and transaction number (found at the bottom of the emailed receipt that was sent to you after purchasing). We will issue you a full and complete refund of your Learning Guide access fee within four (4) to six (6) business days.
                            </p>
                            <p>
                                <strong>20. BACKGROUND CHECKS.</strong>
                            </p>
                            <p>
                                By entering my name, billing address and email address on the Background Check order webpages, I understand and agree that I am providing electronic authorization and consent to Nanny Parent Connection and Employment Background Investigations, Inc. (our background check processor) to process the background check I have selected. I also understand that by marking the check box that I agree to these Terms and Conditions on the Background Check order webpages, I am stating that I have read and consent to these Terms and Conditions and the <a title="Notice to Users of Consumer Reports" href="https://nannyparentconnection.com/wp-content/uploads/2018/03/NoticetoUsersObligationstoUsersUndertheFCRA-EXT040v01-2013-02-21.pdf">Notice to Users of Consumer Reports</a> document.
                            </p>
                            <p>
                                (a) Payment and Refunds: The background check process begins immediately after the payment is processed. Once the background check order has been authorized by the candidate, the payment is non-refundable. If your candidate declines to authorize the background check order, <a title="contact us here" href="mailto:billing@nannyparentconnection.com?subject=Background Check Refund Request">contact us here</a> to request a credit or refund.
                            </p>
                            <p>
                                (b) New York State OCA Fee: In addition to the agreement and disclaimers located on our Background Check webpages, if you purchase a background check and a New York court search is triggered, you agree to have your credit/debit card charged for an additional $100.00 for the <a title="New York state OCA fee" href="https://www.nycourts.gov/apps/chrs/" target="_blank" rel="noopener noreferrer nofollow">New York state OCA fee</a>.
                            </p>
                            <p id="vetted">
                                (c) Vetted Candidate Guarantee: If you purchase a Standard, Premium or Premium Plus background check from our site and upon receiving the completed background check report, find that the candidate was <u>convicted</u> of any of the below listed offenses, <a title="contact us here" href="mailto:info@nannyparentconnection.com?subject=Vetted Candidate Guarantee - Credit Request">contact us here</a> to request a credit for a future background check order of equal or lesser value. Include your name, the name of your candidate, purchase date, and a copy of your receipt with your credit request. Credit requests must be received within thirty (30) days of the date the background check was purchased. Unless otherwise expressly provided under separate terms from Nanny Parent Connection, only one credit issuance is permitted for each background check purchase. Once you have submitted your credit request and have received a confirmation notice, please allow 3-5 business days for the credit to be issued. Covered Felony Convictions: Murder, Aggravated Assault or Battery, Manslaughter, Vehicular Homicide, Animal Cruelty, Larceny, Arson, Burglary, Grand Larceny or Theft, Treason, Rape/Sexual Assault, Kidnapping, Child Pornography, Blackmail and Extortion.
                            </p>
                            <p>
                                <strong>21. AMENDMENTS.</strong> Company reserves the right to amend these Terms. Should Company seek to make such an amendment, which we determine is material in our sole discretion, we shall:
                            </p>
                            <p>
                                (a) Publish on this page the fact an amendment will be made.
                            </p>
                            <p>
                                Should a court of competent jurisdiction rule this Amendment provision invalid, then this Amendment clause shall be terminated as part of this agreement. All amendments to the Terms shall be forward looking.
                            </p>
                            <p>&nbsp;</p>
                        </div>                        
                    </div>
                </div>
            </div>
        </section>
    </main>
</template>
  
<script>
    export default {
        name:'TermsOfUse',
        data() {
            return {
                pageTitle : 'Terms and Conditions of Use | Nanny Parent Connection',
                pageMetaDescription : 'Welcome to Nanny Parent Connection. The following policies, terms and conditions of use are applicable when you view or use the service via our website.',
                pageMetaKeywords : ''
            }  
        },
        mounted() {
            document.title = this.pageTitle;
            document.getElementsByTagName('meta')["description"].content = ""+this.pageMetaDescription+"";
            document.getElementsByTagName('meta')["keywords"].content = ""+this.pageMetaKeywords+"";
            window.scrollTo(0,0);
        },
        methods: { },
        created() {  
            window.scrollTo(0,0);
        }
    }
</script>